### ISSUE TITLE
Changing MTI with Android

### ISSUE THREAD

**Issue by sathamkhussain** [imohsenb/ISO8583-Message-Client-java#18]
Hi,

I have added this as a jar library to the android project. Everything is working fine, but couldn't find a way to change the MTI. 

             `   try {
                           ISOMessage isoMessage = ISOMessageBuilder.Packer(VERSION.V1987)
                            .networkManagement()
                            .mti(MESSAGE_FUNCTION.Request, MESSAGE_ORIGIN.Acquirer)
                            .processCode("920000")
                            .setField(FIELDS.F11_STAN,  "1")
                            .setField(FIELDS.F12_LocalTime,  "023120")
                            .setField(FIELDS.F13_LocalDate,  "0332")
                            .setField(FIELDS.F24_NII_FunctionCode,  "333")
                            .setHeader("1002230000")
                            .build();
                         String mti = isoMessage.getMti();
                        byte[] bytee = isoMessage.getPrimaryBitmap();
                        int length  = isoMessage.length();
                } catch (ISOException e) {
                    e.printStackTrace();
                }
`
It always returns 0800 as MTI.  I am a beginner with ios8583, it would be great if you shed some light on how to change the MTI.

Thanks a lot.
Hussain.

**Comment by sathamkhussain** [comment]
@imohsenb @oluwasayo @adsurg

**Comment by imohsenb** [comment]
Hi, please check [ISO8583 wiki ](https://en.wikipedia.org/wiki/ISO_8583#Message_type_indicator_(MTI)) for more information, it has different tables for each MTI digit

ISOMessageBuilder.Packer(**VERSION.V1987**)  // => 0xxx (ISO 8583 version)
.networkManagement() // =>  x8xx (Message class)
.mti(
  MESSAGE_FUNCTION.Request, // => xx0x (Message function)
  MESSAGE_ORIGIN.Acquirer // => xxx0 (Message origin)
)

**Comment by sathamkhussain** [comment]
@imohsenb Thank you so much for the reply. Is there any way to create an ios message without process code?
