### ISSUE TITLE
System.err: com.imohsenb.ISO8583.exceptions.ISOClientException: Read Timeout

### ISSUE THREAD

**Issue by miaaad** [imohsenb/ISO8583-Message-Client-java#6]
salam be nazareton agha in vase chiyeh man etelaat ro ham dorost mifrestam ama mesle inke chizi daryaft nemishe ,

ye lotfi koni begi elatesh chi mitoneh bashe mamnoon misham

ye soal : emkanesh hast hata ye field eshbah ersal beshe repose daryaft nashe

yani hatman response marbot be zamani hast ke dade haye dorosti ersal beshan

**Comment by imohsenb** [comment]
salam,

omdatan switch haye pardakht age dataye dorost daryaft nakonan javab nemidan.
momkene bekhatere header va ... bashe

**Comment by miaaad** [comment]
khaste nabashid agha ghesmat header fek konam byte kamelsh ro bar nemigardone  va yek chize dige header harf  mesle F E inaro nemipazireh man ino emtehan mikonam 00346000009300 behem faghat 0034600000 ino barmigardone vaghti tabdil mikonam hex

byte[] body = isoMessage.getHeader();

StringBuilder log = new StringBuilder();
                            int i = 0;
                            for (byte b : body) {
                                i++;
                                log.append(String.format("%02x", b));
                            }

                            System.out.println("All Message = " + log);

**Comment by miaaad** [comment]
سلام ببخشی برای قسمت 
F22_EntryMode
F24_NII_FunctionCode

به صورت اتوماتیک یه 
f
میفته جلو اعداد مثلا
765 ===> 765f
میشه

میشه بگید باید چطوری باید این اف رو حذف کرد

اگر ممکنه یه راه ارتباطی بدید یک مقداری صحبت کنیم  یک مقداری کمکی  لطف کنید  داشته باشید ممنونتون میشم

**Comment by imohsenb** [comment]
https://www.linkedin.com/in/imohsenb/

inja behem message bedin, mamnoon
